# Generated by Django 2.0 on 2017-12-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriteUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=255, unique=True)),
                ('yearbook', models.TextField(max_length=300)),
                ('height_feet', models.CharField(max_length=1)),
                ('commencement', models.CharField(max_length=2)),
            ],
        ),
    ]
